[Content]
Packages=lightdm
         lightdm-gtk-greeter-settings
         qt5ct
         qt6ct
         fonts-noto-cjk
         ibus
         ibus-libpinyin
         xfce4
         xfce4-terminal
         gvfs-backends
         xfce4-power-manager
         xfce4-notifyd
         thunar-volman
         celluloid
