[Match]
Distribution=debian

[Distribution]
Release=testing
RepositoryKeyCheck=no
Mirror=http://mirrors.tuna.tsinghua.edu.cn/debian/

[Content]
Packages=
        apt
        dpkg
        git-core
        iproute2
        iputils-ping
        kernel-core
        man-db
        openssh
        passwd
        procps
        python3-minimal
        systemd-boot
