[Match]
Distribution=debian

[Distribution]
Release=testing
RepositoryKeyCheck=no
Repositories=main,contrib,non-free,non-free-firmware
Mirror=http://mirrors.tuna.tsinghua.edu.cn/debian/

[Content]
WithRecommends=yes
Packages=
        apt
        dpkg
        git-core
        iproute2
        iputils-ping
        linux-image-generic
        locales
        login
        man-db
        openssh-client
        passwd
        procps
        python3-minimal
        systemd-boot
        usrmerge
        usr-is-merged
